/**
 * WordPress REST API Client for Astro
 * 
 * Auto-generated by PhantomWP
 * API URL: https://webwork.lkouros.com/wp-json
 */

const WP_API_URL = 'https://webwork.lkouros.com/wp-json';

// WordPress REST API Types
export interface WPPost {
  id: number;
  date: string;
  slug: string;
  title: { rendered: string };
  content: { rendered: string };
  excerpt: { rendered: string };
  author: number;
  featured_media: number;
  categories: number[];
  tags: number[];
  _embedded?: {
    author?: WPUser[];
    'wp:featuredmedia'?: WPMedia[];
    'wp:term'?: Array<WPCategory[] | WPTag[]>;
  };
  // SEO plugin fields (Yoast, Rank Math, AIOSEO)
  yoast_head_json?: any;
  rank_math?: any;
  aioseo?: any;
}

export interface WPPage {
  id: number;
  date: string;
  slug: string;
  title: { rendered: string };
  content: { rendered: string };
  excerpt: { rendered: string };
  author: number;
  featured_media: number;
  parent: number;
  _embedded?: {
    author?: WPUser[];
    'wp:featuredmedia'?: WPMedia[];
  };
  // SEO plugin fields (Yoast, Rank Math, AIOSEO)
  yoast_head_json?: any;
  rank_math?: any;
  aioseo?: any;
}

// Unified SEO data structure
export interface WPSEOData {
  title?: string;
  description?: string;
  canonicalUrl?: string;
  ogTitle?: string;
  ogDescription?: string;
  ogImage?: string;
  ogType?: string;
  twitterTitle?: string;
  twitterDescription?: string;
  twitterImage?: string;
  twitterCard?: string;
  robots?: { index?: boolean; follow?: boolean };
  focusKeyword?: string;
}

export interface WPMedia {
  id: number;
  slug: string;
  title: { rendered: string };
  alt_text: string;
  source_url: string;
  media_details: {
    width: number;
    height: number;
    sizes: Record<string, { source_url: string; width: number; height: number }>;
  };
}

export interface WPCategory {
  id: number;
  name: string;
  slug: string;
  count: number;
  description: string;
}

export interface WPTag {
  id: number;
  name: string;
  slug: string;
  count: number;
  description: string;
}

export interface WPUser {
  id: number;
  name: string;
  slug: string;
  description: string;
  avatar_urls: Record<string, string>;
}

// Fetch helpers
async function wpFetch<T>(endpoint: string, params: Record<string, any> = {}, defaultValue?: T): Promise<T> {
  const url = new URL(`${WP_API_URL}/wp/v2/${endpoint}`);
  
  Object.entries(params).forEach(([key, value]) => {
    if (value !== undefined && value !== null) {
      url.searchParams.set(key, String(value));
    }
  });
  
  try {
    const response = await fetch(url.toString());
    
    if (!response.ok) {
      console.error(`WordPress API error: ${response.status} ${response.statusText}`);
      return defaultValue as T;
    }
    
    return response.json();
  } catch (error) {
    console.error(`WordPress API connection failed for ${endpoint}:`, error instanceof Error ? error.message : error);
    return defaultValue as T;
  }
}

// Posts
export async function getPosts(options: {
  page?: number;
  perPage?: number;
  search?: string;
  categories?: number[];
  tags?: number[];
  author?: number;
} = {}): Promise<WPPost[]> {
  return wpFetch<WPPost[]>('posts', {
    page: options.page,
    per_page: options.perPage || 10,
    search: options.search,
    categories: options.categories?.join(','),
    tags: options.tags?.join(','),
    author: options.author,
    _embed: true,
  }, []);
}

export async function getPost(slug: string): Promise<WPPost | null> {
  const posts = await wpFetch<WPPost[]>('posts', { slug, _embed: true }, []);
  return posts && posts.length > 0 ? posts[0] : null;
}

export async function getPostById(id: number): Promise<WPPost | null> {
  return wpFetch<WPPost | null>(`posts/${id}`, { _embed: true }, null);
}

export async function getAllPosts(): Promise<WPPost[]> {
  const allPosts: WPPost[] = [];
  let page = 1;
  let hasMore = true;
  
  while (hasMore) {
    const posts = await getPosts({ page, perPage: 100 });
    if (!posts || posts.length === 0) {
      hasMore = false;
    } else {
      allPosts.push(...posts);
      hasMore = posts.length === 100;
      page++;
    }
  }
  
  return allPosts;
}

// Pages
export async function getPages(options: {
  page?: number;
  perPage?: number;
  search?: string;
  parent?: number;
} = {}): Promise<WPPage[]> {
  return wpFetch<WPPage[]>('pages', {
    page: options.page,
    per_page: options.perPage || 10,
    search: options.search,
    parent: options.parent,
    _embed: true,
  }, []);
}

export async function getPage(slug: string): Promise<WPPage | null> {
  const pages = await wpFetch<WPPage[]>('pages', { slug, _embed: true }, []);
  return pages && pages.length > 0 ? pages[0] : null;
}

export async function getPageById(id: number): Promise<WPPage | null> {
  return wpFetch<WPPage | null>(`pages/${id}`, { _embed: true }, null);
}

export async function getAllPages(): Promise<WPPage[]> {
  const allPages: WPPage[] = [];
  let page = 1;
  let hasMore = true;
  
  while (hasMore) {
    const pages = await getPages({ page, perPage: 100 });
    if (!pages || pages.length === 0) {
      hasMore = false;
    } else {
      allPages.push(...pages);
      hasMore = pages.length === 100;
      page++;
    }
  }
  
  return allPages;
}

// Media
export async function getMedia(options: {
  page?: number;
  perPage?: number;
  search?: string;
} = {}): Promise<WPMedia[]> {
  return wpFetch<WPMedia[]>('media', {
    page: options.page,
    per_page: options.perPage || 10,
    search: options.search,
  }, []);
}

export async function getMediaById(id: number): Promise<WPMedia | null> {
  return wpFetch<WPMedia | null>(`media/${id}`, {}, null);
}

// Categories
export async function getCategories(): Promise<WPCategory[]> {
  return wpFetch<WPCategory[]>('categories', { per_page: 100 }, []);
}

export async function getCategoryBySlug(slug: string): Promise<WPCategory | null> {
  const categories = await wpFetch<WPCategory[]>('categories', { slug }, []);
  return categories && categories.length > 0 ? categories[0] : null;
}

// Tags
export async function getTags(): Promise<WPTag[]> {
  return wpFetch<WPTag[]>('tags', { per_page: 100 }, []);
}

export async function getTagBySlug(slug: string): Promise<WPTag | null> {
  const tags = await wpFetch<WPTag[]>('tags', { slug }, []);
  return tags && tags.length > 0 ? tags[0] : null;
}

// Users/Authors
export async function getUsers(): Promise<WPUser[]> {
  return wpFetch<WPUser[]>('users', { per_page: 100 }, []);
}

export async function getUserById(id: number): Promise<WPUser | null> {
  return wpFetch<WPUser | null>(`users/${id}`, {}, null);
}

export async function getUserBySlug(slug: string): Promise<WPUser | null> {
  const users = await wpFetch<WPUser[]>('users', { slug }, []);
  return users && users.length > 0 ? users[0] : null;
}

// Helper to get featured image URL from embedded data
export function getFeaturedImageUrl(post: WPPost | WPPage, size: string = 'full'): string | null {
  const media = post._embedded?.['wp:featuredmedia']?.[0];
  if (!media) return null;
  
  if (size === 'full') {
    return media.source_url;
  }
  
  return media.media_details?.sizes?.[size]?.source_url || media.source_url;
}

// Helper to get author from embedded data
export function getAuthor(post: WPPost | WPPage): WPUser | null {
  return post._embedded?.author?.[0] || null;
}

// Helper to get categories from embedded data (posts only)
export function getPostCategories(post: WPPost): WPCategory[] {
  const terms = post._embedded?.['wp:term'];
  if (!terms) return [];
  return (terms[0] as WPCategory[]) || [];
}

// Helper to get tags from embedded data (posts only)
export function getPostTags(post: WPPost): WPTag[] {
  const terms = post._embedded?.['wp:term'];
  if (!terms) return [];
  return (terms[1] as WPTag[]) || [];
}

// Helper to format dates
export function formatDate(
  dateString: string,
  options: Intl.DateTimeFormatOptions = { year: 'numeric', month: 'long', day: 'numeric' }
): string {
  return new Date(dateString).toLocaleDateString('en-US', options);
}

/**
 * Strip HTML tags from content
 * @param html - HTML string to strip
 * @returns Plain text string
 */
export function stripHtml(html: string): string {
  if (!html) return '';
  return html
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Truncate text to a maximum length with ellipsis
 * @param text - Text to truncate
 * @param maxLength - Maximum length (default: 150)
 * @returns Truncated text
 */
export function truncate(text: string, maxLength: number = 150): string {
  if (!text) return '';
  if (text.length <= maxLength) return text;
  return text.substring(0, maxLength).trim() + '...';
}

// Custom Post Type helpers
export async function getCustomPostType(restBase: string, options: {
  page?: number;
  perPage?: number;
  search?: string;
} = {}): Promise<any[]> {
  return wpFetch<any[]>(restBase, {
    page: options.page,
    per_page: options.perPage || 100,
    search: options.search,
    _embed: true,
  }, []);
}

export async function getCustomPostTypeItem(restBase: string, slug: string): Promise<any | null> {
  const items = await wpFetch<any[]>(restBase, { slug, _embed: true }, []);
  return items && items.length > 0 ? items[0] : null;
}

export async function getCustomPostTypeById(restBase: string, id: number): Promise<any | null> {
  return wpFetch<any | null>(`${restBase}/${id}`, { _embed: true }, null);
}

// ============================================================================
// Media URL Rewriting (for local images)
// ============================================================================

// Import media map - this file should exist (even if empty: {})
// If you've downloaded media, this maps WordPress URLs to local paths
import mediaUrlMap from './media-map.json';

export function loadMediaMap(): void {
  // No-op for backwards compatibility - map is loaded via import
}

/**
 * Extract the base filename from a WordPress URL, removing size suffixes
 * e.g., "image-1024x585.png" -> "image.png"
 */
function extractBaseFilename(url: string): string | null {
  if (!url) return null;
  
  // Get filename from URL or path
  const parts = url.split('/');
  let filename = parts[parts.length - 1];
  
  // Remove query string
  filename = filename.split('?')[0];
  
  // Remove WordPress size suffix (e.g., -1024x585, -300x200, etc.)
  // Pattern: -[digits]x[digits] before the extension
  filename = filename.replace(/-\d+x\d+(?=\.[^.]+$)/, '');
  
  return filename.toLowerCase();
}

export function getLocalImageUrl(originalUrl: string | null): string | null {
  if (!originalUrl) return null;
  const map = mediaUrlMap as Record<string, string>;
  
  // Direct match
  if (map[originalUrl]) return map[originalUrl];
  
  // Try to match by filename (handles size variants like -1024x585.png)
  const filename = extractBaseFilename(originalUrl);
  if (filename) {
    for (const [, localPath] of Object.entries(map)) {
      const localFilename = extractBaseFilename(localPath);
      if (localFilename && localFilename === filename) {
        return localPath;
      }
    }
  }
  
  return originalUrl;
}

/**
 * Rewrite image URLs in HTML content to use local paths
 * Handles WordPress size variants (e.g., image-1024x585.png -> image.png)
 */
export function rewriteContentUrls(content: string): string {
  const map = mediaUrlMap as Record<string, string>;
  if (Object.keys(map).length === 0) return content;
  
  // Build a filename -> local path lookup
  const filenameMap: Record<string, string> = {};
  for (const [, localPath] of Object.entries(map)) {
    const baseFilename = extractBaseFilename(localPath);
    if (baseFilename) {
      filenameMap[baseFilename] = localPath;
    }
  }
  
  // First, do exact URL replacements
  let result = content;
  for (const [originalUrl, localPath] of Object.entries(map)) {
    result = result.split(originalUrl).join(localPath);
  }
  
  // Then, find and replace WordPress media URLs by filename matching
  // Match URLs that look like WordPress uploads
  const wpUrlPattern = /https?:\/\/[^"'\s]+\/wp-content\/uploads\/[^"'\s]+\.(jpg|jpeg|png|gif|webp|svg)/gi;
  
  result = result.replace(wpUrlPattern, (wpUrl) => {
    const baseFilename = extractBaseFilename(wpUrl);
    if (baseFilename && filenameMap[baseFilename]) {
      return filenameMap[baseFilename];
    }
    return wpUrl;
  });
  
  // Remove srcset and sizes attributes - they contain mixed remote/local URLs
  // This ensures the browser uses only the src attribute with our local image
  result = result.replace(/\s*srcset="[^"]*"/gi, '');
  result = result.replace(/\s*sizes="[^"]*"/gi, '');
  
  return result;
}

export function getLocalFeaturedImageUrl(
  post: WPPost | WPPage,
  size: 'thumbnail' | 'medium' | 'large' | 'full' = 'full'
): string | null {
  const remoteUrl = getFeaturedImageUrl(post, size);
  return getLocalImageUrl(remoteUrl);
}

// ============================================================================
// SEO Plugin Integration
// ============================================================================

/**
 * Detect which SEO plugin is providing data
 */
export function detectSEOPlugin(post: WPPost | WPPage | any): 'yoast' | 'rankmath' | 'aioseo' | null {
  if (post.yoast_head_json) return 'yoast';
  if (post.rank_math) return 'rankmath';
  if (post.aioseo) return 'aioseo';
  return null;
}

/**
 * Extract unified SEO data from any supported plugin
 * Supports: Yoast SEO, Rank Math, All in One SEO
 */
export function extractSEOData(post: WPPost | WPPage | any): WPSEOData {
  const seo: WPSEOData = {};
  
  // Try Yoast SEO first (most common)
  if (post.yoast_head_json) {
    const yoast = post.yoast_head_json;
    seo.title = yoast.title;
    seo.description = yoast.description;
    seo.canonicalUrl = yoast.canonical;
    seo.ogTitle = yoast.og_title;
    seo.ogDescription = yoast.og_description;
    seo.ogImage = yoast.og_image?.[0]?.url;
    seo.ogType = yoast.og_type;
    seo.twitterTitle = yoast.twitter_title;
    seo.twitterDescription = yoast.twitter_description;
    seo.twitterImage = yoast.twitter_image;
    seo.twitterCard = yoast.twitter_card;
    if (yoast.robots) {
      seo.robots = {
        index: yoast.robots.index !== 'noindex',
        follow: yoast.robots.follow !== 'nofollow',
      };
    }
    return seo;
  }
  
  // Try Rank Math
  if (post.rank_math) {
    const rm = post.rank_math;
    seo.title = rm.title;
    seo.description = rm.description;
    seo.canonicalUrl = rm.canonical_url;
    seo.ogTitle = rm.og_title;
    seo.ogDescription = rm.og_description;
    seo.ogImage = rm.og_image;
    seo.twitterTitle = rm.twitter_title;
    seo.twitterDescription = rm.twitter_description;
    seo.twitterImage = rm.twitter_image;
    seo.focusKeyword = rm.focuskw;
    if (rm.robots) {
      seo.robots = {
        index: !rm.robots.includes('noindex'),
        follow: !rm.robots.includes('nofollow'),
      };
    }
    return seo;
  }
  
  // Try All in One SEO
  if (post.aioseo) {
    const aio = post.aioseo;
    seo.title = aio.title;
    seo.description = aio.description;
    seo.canonicalUrl = aio.canonical;
    seo.ogTitle = aio.og_title;
    seo.ogDescription = aio.og_description;
    seo.ogImage = aio.og_image;
    seo.twitterTitle = aio.twitter_title;
    seo.twitterDescription = aio.twitter_description;
    seo.twitterImage = aio.twitter_image;
    seo.twitterCard = aio.twitter_card;
    seo.focusKeyword = aio.keyphrases?.focus?.keyphrase;
    seo.robots = {
      index: !aio.robots_noindex,
      follow: !aio.robots_nofollow,
    };
    return seo;
  }
  
  return seo;
}

/**
 * Get SEO title with fallback to post/page title
 */
export function getSEOTitle(post: WPPost | WPPage | any): string {
  const seo = extractSEOData(post);
  return seo.title || post.title?.rendered || '';
}

/**
 * Get SEO description with fallback to excerpt
 */
export function getSEODescription(post: WPPost | WPPage | any): string {
  const seo = extractSEOData(post);
  if (seo.description) return seo.description;
  return stripHtml(post.excerpt?.rendered || '');
}

/**
 * Get OG image with fallback to featured image
 */
export function getSEOImage(post: WPPost | WPPage | any): string | null {
  const seo = extractSEOData(post);
  if (seo.ogImage) return seo.ogImage;
  return getFeaturedImageUrl(post, 'large');
}
